//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian


#include "GasHit.hh"

G4ThreadLocal G4Allocator<GasHit> *GasHitAllocator = 0;

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

GasHit::GasHit()
{
    this->Init();
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

GasHit::GasHit(const GasHit &right) : G4VHit(right)
{
    this->Init();
    pdgID = right.pdgID;
    prodID = right.prodID;
    trackID = right.trackID;
    Edep = right.Edep;
    stepL = right.stepL;
    prePos = right.prePos;
    postPos = right.postPos;
    isFirstDeposit = right.isFirstDeposit;
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

GasHit::GasHit(const G4Step *right)
{
    this->Init();
    pdgID = right->GetTrack()->GetParticleDefinition()->GetPDGEncoding();
    prodID = right->GetTrack()->GetParentID();
    trackID = right->GetTrack()->GetTrackID();
    Edep = right->GetTotalEnergyDeposit();
    stepL = right->GetStepLength();
    prePos = right->GetPostStepPoint()->GetPosition();
    postPos = right->GetPreStepPoint()->GetPosition();
    isFirstDeposit = right->IsFirstStepInVolume();
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

GasHit::~GasHit()
{
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

const GasHit &GasHit::operator=(const GasHit &right)
{
    this->Init();
    pdgID = right.pdgID;
    prodID = right.prodID;
    trackID = right.trackID;
    Edep = right.Edep;
    stepL = right.stepL;
    prePos = right.prePos;
    postPos = right.postPos;
    isFirstDeposit = right.isFirstDeposit;
    return *this;
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

int GasHit::operator==(const GasHit &) const
{
    return 0;
}

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

void GasHit::Init()
{
    pdgID = 0;
    prodID = 0;
    trackID = 0;
    Edep = 0.;
    stepL = 0.;
    prePos = G4ThreeVector(0., 0., 0.);
    postPos = G4ThreeVector(0., 0., 0.);
    isFirstDeposit = false;
}
