//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian


#ifndef GasSD_hh
#define GasSD_hh 1

#include "G4VSensitiveDetector.hh"
#include "GasHit.hh"

class G4Step;
class G4HCofThisEvent;
class G4TouchableHistory;

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

class GasSD : public G4VSensitiveDetector
{
  public:
    GasSD(G4String);
    virtual ~GasSD();

      virtual void Initialize(G4HCofThisEvent* HCE);
      virtual G4bool ProcessHits(G4Step* aStep,G4TouchableHistory* ROhist);
      virtual void EndOfEvent(G4HCofThisEvent* HCE);
      virtual void clear();
      virtual void DrawAll();
      virtual void PrintAll();
		int akaakaaka =0;
      
  private:
    GasHitCollection*     fHitsCollection;
};

#endif
