//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef MyDetectorMessenger_h
#define MyDetectorMessenger_h

#include "globals.hh"
#include "G4UImessenger.hh"

class G4UIdirectory;
class G4UIcmdWithAString;
class G4UIcmdWithADoubleAndUnit;
class G4UIcmdWithoutParameter;
class G4UIcmdWithADouble;
class MyDetectorConstruction;

//-------------------------------
// MyDetectorMessenger class that defines commands for MyDetectorConstruction.
class MyDetectorMessenger : public G4UImessenger
{
public:
  MyDetectorMessenger(MyDetectorConstruction *);
  virtual ~MyDetectorMessenger();

  virtual void SetNewValue(G4UIcommand *, G4String);

private:
  MyDetectorConstruction *fDetectorConstruction;

  G4UIdirectory *fMyDirectory;
  G4UIdirectory *fDetDirectory;

  G4UIcmdWithADoubleAndUnit* fWorldSizeXCmd;
  G4UIcmdWithADoubleAndUnit* fWorldSizeYCmd;
  G4UIcmdWithADoubleAndUnit* fWorldSizeZCmd;
  G4UIcmdWithAString       * fWorldMatCmd;
  G4UIcmdWithADoubleAndUnit* fWindowSizeXCmd;
  G4UIcmdWithADoubleAndUnit* fWindowSizeYCmd;
  G4UIcmdWithADoubleAndUnit* fWindowSizeZCmd;
  G4UIcmdWithAString       * fWindowMatCmd;
  G4UIcmdWithADoubleAndUnit* fGasSizeXCmd;
  G4UIcmdWithADoubleAndUnit* fGasSizeYCmd;
  G4UIcmdWithADoubleAndUnit* fGasSizeZCmd;
  G4UIcmdWithAString       * fGasMatCmd;


  G4UIcmdWithoutParameter *fUpdateCmd;
};

#endif
