//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian


#ifndef WindowSD_hh
#define WindowSD_hh 1

#include "G4VSensitiveDetector.hh"
#include "WindowHit.hh"

class G4Step;
class G4HCofThisEvent;
class G4TouchableHistory;

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

class WindowSD : public G4VSensitiveDetector
{
  public:
    WindowSD(G4String);
    virtual ~WindowSD();

      virtual void Initialize(G4HCofThisEvent* HCE);
      virtual G4bool ProcessHits(G4Step* aStep,G4TouchableHistory* ROhist);
      virtual void EndOfEvent(G4HCofThisEvent* HCE);
      virtual void clear();
      virtual void DrawAll();
      virtual void PrintAll();
		int einwindows = 0;
      
  private:
    WindowHitCollection*     fHitsCollection;
};

#endif
