//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian


#ifndef WindowHit_h
#define WindowHit_h

#include "G4THitsCollection.hh"
#include "G4Allocator.hh"
#include "G4Step.hh"
#include "G4VHit.hh"

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

class WindowHit : public G4VHit
{
  public:
    WindowHit();
    ~WindowHit();
    WindowHit(const WindowHit &);
    WindowHit(const G4Step *);

    const WindowHit &operator=(const WindowHit &);
    int operator==(const WindowHit &) const;
    inline void *operator new(size_t);
    inline void operator delete(void *);

    void Init();

    inline G4int GetPDGID() { return pdgID; }
    inline G4int GetProducerID() { return prodID; }
    inline G4int GetTrackID() { return trackID; }
    inline G4double GetEdep() { return Edep; }
    inline G4double GetStepLength() { return stepL; }
    inline G4ThreeVector GetPostPosition() { return postPos; }
    inline G4ThreeVector GetPrePosition() { return prePos; }
    inline G4bool IsFirstDeposit() { return isFirstDeposit; }

    inline void SetPDGID(G4int id) { pdgID = id; }
    inline void SetProducerID(G4int id) { prodID = id; }
    inline void SetTrackID(G4int id) { trackID = id; }
    inline void SetEdep(G4double edep) { Edep = edep; }
    inline void SetStepLength(G4double length) { stepL = length; }
    inline void SetPostPosition(G4ThreeVector pos) { postPos = pos; }
    inline void SetPrePosition(G4ThreeVector pos) { prePos = pos; }
    inline void SetFirstDepositFlag() { isFirstDeposit = true; }

  private:
    G4int pdgID;
    G4int prodID;
    G4int trackID;
    G4double Edep;
    G4double stepL;
    G4ThreeVector prePos;
    G4ThreeVector postPos;
    G4bool isFirstDeposit;
};

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

typedef G4THitsCollection<WindowHit> WindowHitCollection;

extern G4ThreadLocal G4Allocator<WindowHit> *WindowHitAllocator;

//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

inline void *WindowHit::operator new(size_t)
{
    if (!WindowHitAllocator)
        WindowHitAllocator = new G4Allocator<WindowHit>;
    return (void *)WindowHitAllocator->MallocSingle();
}
//....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo....

inline void WindowHit::operator delete(void *aHit)
{
    WindowHitAllocator->FreeSingle((WindowHit *)aHit);
}

#endif
